version: '3.8'
services:
  auth:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET=
      - JWT_AUDIENCE=auth
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_MIN=15
      - REFRESH_TOKEN_EXPIRES_DAYS=7
  wallet:
    build:
      context: ./services/wallet_service
      dockerfile: Dockerfile
    container_name: wallet_service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET=
      - JWT_AUDIENCE=wallet
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_MIN=15
  shop:
    build:
      context: ./services/shop_service
      dockerfile: Dockerfile
    container_name: shop_service
    ports:
      - "8002:8002"
    environment:
      - JWT_SECRET=
      - JWT_AUDIENCE=shop
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRES_MIN=15
